### PR TITLE
bug(expansionhunter): switches vt svdb order

### LINKED ISSUE #1169: STR calls in Trio
Good day Sir/Madam
this case shows some strange calls of STR ATXN8OS from the individuals in a trio. Example; 2019-22270-04 has 4 alleles/calls.
https://scout.scilifelab.se/cust002/F0028964-2/str/variants?variant_type=clinical#

Found by Helena Malmgren and she would appriciate to be on the issue as well.

Enjoy Wednesday

### PR DESCRIPTION
**Pull request by jemten**
### This PR fixes:
- fixes representation of multiallelic str calls
- resolves #1169 

### How to test:

- Automatic and continuous test pass

### Expected outcome:
- Installation, unit and integration tests pass

### Review:
- [x] Code review
- [x] New code is executed and covered by tests
- [x] Tests pass

### CODE REVIEW

File: lib/MIP/Recipes/Analysis/Expansionhunter.pm [hunk 1]
```diff
@@ -320,48 +322,58 @@ sub analysis_expansionhunter {
...
+          . $UNDERSCORE
+          . $sample_id
+          . $outfile_suffix;
 
     }
     say {$filehandle} q{wait}, $NEWLINE;
 
+    ## Split multiallelic variants
+    say {$filehandle} q{## Split multiallelic variants};
+    my $vt_file_paths = each_array( @vt_infile_paths, @vt_outfile_paths );
```
Comment (henrikstranneheim) [inline lib/MIP/Recipes/Analysis/Expansionhunter.pm]: Add comment on returning array iter object

File: lib/MIP/Recipes/Analysis/Expansionhunter.pm [hunk 2]
```diff
@@ -320,48 +322,58 @@ sub analysis_expansionhunter {
...
+
+  VT_SAMPLE_FILES:
```
Comment (henrikstranneheim) [inline lib/MIP/Recipes/Analysis/Expansionhunter.pm]: VT_SAMPLE_ITER:
